### PR TITLE
Stylus Port

### PR DESCRIPTION
**Pull request by Narkoleptika**
Adds a stylus port as discussed in #4

### CODE REVIEW

**Comment by aaronjamesyoung** [comment]
merged, boom. I'm going to write a bit more in that main README when I have a chance. Let me know how/if you'd like to be credited. Thanks again!

**Comment by Narkoleptika** [comment]
That's awesome, Aaron! Thank you!

When you're working on the main README, can you fix something for me? I missed a spot on line 176 in the stylus README. There's a stray bracket at the end of the code block that should be removed.

If yuh want, a `[Narkoleptika](https://github.com/Narkoleptika)` should be sufficient. 😃

**Comment by aaronjamesyoung** [comment]
Hey, while I've got your attention here...

I decided to fix something that's been bugging me for a while - I don't really like the whole "specify a number and we'll assume it's pixels" thing, since px aren't really always the unit we want to use.

So I pushed commit f108e30 which allows the user to specify any unit measurement. It also contains fallbacks to still interpret a unitless number as pixels, so as to not bork anyone's code. I've tested this out on Codepen in both Sass and Stylus and everything seems to work fine.

When you have a chance, would you mind taking a minute or two to review the diff, let me know if there's something I should be doing better, and paste the updates into your codepen? Thanks again!

**Comment by Narkoleptika** [comment]
Excellent idea!

I played around with it and updated the codepen with the new version. 👌

There was only one change I would make and it's entirely stylistic (ha!). I left a comment in the commit [here](https://github.com/aaronjamesyoung/simplest-flexbox-grid/commit/f108e3005a71d66ce3e29d05e0dcfc537df3789d#r28140578), describing the change.

If you decide that it's worth making the change, let me know and I'll update the codepen.

Also, feel free to fork my codepen and update the link to maintain your autonomy with future updates.

Otherwise, I'm happy to update the codepen with future updates. Just let me know when it's necessary and I'll try to update in a timely manner.

**Pull request merged**
